version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"

  medusa-backend:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      ADMIN_CORS: http://localhost:7000,http://localhost:9000
      STORE_CORS: http://localhost:8000
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: yarn start

volumes:
  pgdata:
